### ISSUE TITLE
ROCData not defined

### ISSUE THREAD

**Issue by arshak** [diegozea/ROC.jl#2]
using ROC gives the following error

ROCData not defined
while loading /Users/arshakn/.julia/v0.3/ROC/src/ROC.jl, in expression starting on line 4
while loading In[97], in expression starting on line 1

 in include at /Applications/Julia-0.3.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51

versioninfo()
Julia Version 0.3.6
Commit 0c24dca\* (2015-02-17 22:12 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by droidicus** [comment]
I had the same error, and this fixed the problem for me... Many filesystems are not case sensitive, causing the roc.jl and ROC.jl files in this repository to conflict. I had to do the following to make the repo work and pass the tests:

```
1) Download the repo as a zip file and unpack into my ./julia/v0.3/ folder
2) Keep the name of ROC.jl the same
3) Rename roc.jl to roc_main.jl
4) edit ROC.jl to change include("roc.jl") to include("roc_main.jl")
```

**Comment by diegozea** [comment]
Thanks @droidicus !

**Comment by diegozea** [comment]
`roc.jl` file was renamed. It should work now after a `Pkg.update()` ;)
